### ISSUE TITLE
在侧栏输入时，journals页面会不受控制的自主滚动

### ISSUE THREAD

**Issue by taogb2020** [b-yp/loseq-typewriter-mode#3]
我在通过右侧栏输入时，journals页面会自己滚动
![自动滚动问题-0719](https://github.com/b-yp/loseq-typewriter-mode/assets/72112574/7ae859cd-5c72-439e-8d6f-799552a7349f)
停用这个插件后，就好了
![自动滚动问题-删除打字机插件后-0720](https://github.com/b-yp/loseq-typewriter-mode/assets/72112574/90514806-f7c9-444a-ac87-2e4d6024eaf1)
但是，就没有打字机功能了

**Comment by b-yp** [comment]
感谢大佬发现的 bug ， 新版本已修复
