### ISSUE TITLE
For long paragraph in a block, the typewriter mode focuses on the first line of the block but not where the cursor is.

### ISSUE THREAD

**Issue by xiaodl813** [b-yp/loseq-typewriter-mode#7]
Hello,

When I edit a long paragraph in a block, I found that the typewriter mode focuses on the first line of the block but not where the cursor is. (Shown below in the gif)

![@A functional role for both γ‐aminobutyric acid (GABA) transporter‐1 and GABA transporter‐3 in the modulation of extracellular GABA and GABAergic tonic conductances in the rat hippocampus 2023-10-19 11-02-44](https://github.com/b-yp/loseq-typewriter-mode/assets/50045896/f8c1469c-b4a4-4489-b321-d65301baa283)

(If this gif is not clear enough, please remind me that I can upload a much more clear one.)

Thank you!

**Comment by b-yp** [comment]
This is indeed a bug

**Comment by b-yp** [comment]
This is a Bug.

**Comment by b-yp** [comment]
fixed https://github.com/b-yp/loseq-typewriter-mode/pull/9

**Comment by xiaodl813** [comment]
> fixed #9

It worked! Thank you a lot!
